import type { Metadata } from 'next'
import { GeistMono } from 'geist/font/mono'
import '@/styles/globals.css'
import Layout from '@/app/components/layout'
import Script from 'next/script'
export const metadata: Metadata = {
  title: 'Depin Alliance',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
      </head>
      <body className={`${GeistMono.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
