import type { Metadata } from 'next'
import { GeistMono } from 'geist/font/mono'
import '@/styles/globals.css'
import Layout from '@/app/components/layout'
import Script from 'next/script'
import { GoogleAnalytics } from '@next/third-parties/google'
export const metadata: Metadata = {
  title: 'Depin Alliance',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
      </head>
      <body className={`${GeistMono.variable}`}>
        <Layout>{children}</Layout>
      </body>
      <GoogleAnalytics gaId="G-QM3ZVFLQDK" />
    </html>
  )
}
